// This file was autogenerated by lib/google-closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('js/findzen.Log.js', ['findzen.Log'], []);
goog.addDependency('js/loader.js', ['namespace.project'], ['findzen.Log', 'namespace.project.App']);
goog.addDependency('js/namespace.project.App.js', ['namespace.project.App'], ['findzen.Log', 'namespace.project.Controller', 'namespace.project.Model', 'namespace.project.View']);
goog.addDependency('js/namespace.project.Controller.js', ['namespace.project.Controller'], ['findzen.Log', 'namespace.project.Model', 'namespace.project.View']);
goog.addDependency('js/namespace.project.Model.js', ['namespace.project.Model'], ['findzen.Log']);
goog.addDependency('js/namespace.project.View.js', ['namespace.project.View'], ['findzen.Log']);
